openapi: 3.0.0
info:
  title: CP Platform API documentation
  version: 1.0.0
  description: API documentation for CP Platform covering Authentication, Dashboard, and Problem List.

servers:
  - url: http://127.0.0.1:8000
    description: Local development server

paths:
  /authentication/api/records/:
    get:
      summary: Get all records
      tags:
        - Authentication
      responses:
        '200':
          description: A list of records
    post:
      summary: Create a new record
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Record'
      responses:
        '201':
          description: Record created

  /dashboard/api/:
    get:
      summary: Get dashboard data
      tags:
        - Dashboard
      responses:
        '200':
          description: Dashboard data response

  /problem_list/api/:
    get:
      summary: List all problems
      tags:
        - Problem List
      responses:
        '200':
          description: A list of problems
    post:
      summary: Add a new problem
      tags:
        - Problem List
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Problem'
      responses:
        '201':
          description: Problem created

components:
  schemas:
    Record:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          type: string
        city:
          type: string
        state:
          type: string
        zipcode:
          type: string

    Problem:
      type: object
      properties:
        title:
          type: string
        editorial_link:
          type: string
        video_link:
          type: string
        code:
          type: string
        rating:
          type: integer
        ac_rate:
          type: boolean
        source:
          type: string
        starred:
          type: boolean
        status:
          type: string
          enum:
            - not_started
            - reading
            - practicing
            - complete
            - skipped
            - ignored
        is_external:
          type: boolean
        external_url:
          type: string
