# Generated by Django 5.2 on 2025-06-15 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('editorial_link', models.URLField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('code', models.TextField()),
                ('rating', models.IntegerField(default=800)),
                ('ac_rate', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('starred', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('reading', 'Reading'), ('practicing', 'Practicing'), ('complete', 'Complete'), ('skipped', 'Skipped'), ('ignored', 'Ignored')], default='not_started', max_length=20)),
                ('is_external', models.BooleanField(default=False)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('bookmarked_by', models.ManyToManyField(blank=True, related_name='bookmarked_problems', through='dashboard.Bookmark', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rating', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProblemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('reading', 'Reading'), ('practicing', 'Practicing'), ('complete', 'Complete'), ('skipped', 'Skipped'), ('ignored', 'Ignored')], default='not_started', max_length=20)),
                ('bookmarked', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_list_problem_statuses', to='problem_list.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_list_problem_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'problem')},
            },
        ),
    ]
